#
# Environment variables for configuring the stack
# are prefixed with OPS_ (stands for OpenPypeStack).
#
# Variables for OpenPype server backend are prefixed
# with OPENPYPE
#

version: "3.3"
services:
  postgres:
    image: postgres
    ports:
      - "${OPS_PG_LISTEN-127.0.0.1:5432}:5432"
    environment:
      - "POSTGRES_USER=pypeusr"
      - "POSTGRES_PASSWORD=pypepass"
      - "POSTGRES_DB=pype"
    volumes:
      - db:/var/lib/postgresql
      - ./openpype4-backend/schemas/schema.public.sql:/docker-entrypoint-initdb.d/10-schema.sql
    restart: unless-stopped

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: unless-stopped

  backend:
    build: "./openpype4-backend"
    volumes:
        - "./openpype4-backend:/openpype"
    ports:
        - "${OPS_BACKEND_LISTEN-127.0.0.1:5000}:5000"
    working_dir: /openpype
    command: ./run.sh --reload --log-level warning --host 0.0.0.0 --port 5000
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    environment:
      - "OPENPYPE_DISCORD_CLIENT_ID=${OPENPYPE_DISCORD_CLIENT_ID-}"
      - "OPENPYPE_DISCORD_CLIENT_SECRET=${OPENPYPE_DISCORD_CLIENT_SECRET-}"
      - "OPENPYPE_GOOGLE_CLIENT_ID=${OPENPYPE_GOOGLE_CLIENT_ID-}"
      - "OPENPYPE_GOOGLE_CLIENT_SECRET=${OPENPYPE_GOOGLE_CLIENT_SECRET-}"

  caddy:
    image: caddy
    volumes:
      - "./support/Caddyfile:/etc/caddy/Caddyfile"
      - "./openpype4-frontend/build:/frontend"
    ports:
      - "${OPS_HTTP_PORT-80}:80"
      - "${OPS_HTTPS_PORT-443}:443"
    environment:
      - "OPENPYPE_HOSTNAME=${OPENPYPE_HOSTNAME-*:80}"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  db: {}
